name: Package Plugin

on:
  release:
    types: [created]

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare folder for ZIP
        run: |
          mkdir waldjugend-plugin
          rsync -av --progress ./waldjugend-plugin/ waldjugend-plugin/ \
            --exclude='.git*' \
            --exclude='.github/*' \
            --exclude='.chglog/*' \
            --exclude='tests/*'

      - name: Create ZIP
        run: |
          zip -r waldjugend-plugin.zip waldjugend-plugin

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: waldjugend-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
