name: Package Plugin

on:
  release:
    types: [published]

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up release version and zip name
        id: vars
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          ZIPNAME="waldjugend-plugin-${TAG}.zip"
          echo "ZIPNAME=$ZIPNAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Prepare plugin directory
        run: |
          mkdir -p waldjugend-plugin
          rsync -av \
            --exclude='.git*' \
            --exclude='.github' \
            --exclude='.chglog' \
            --exclude='waldjugend-plugin' \
            ./ waldjugend-plugin/
          ls -la waldjugend-plugin

      - name: Create the zip file
        run: |
          zip -r "$ZIPNAME" waldjugend-plugin

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIPNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}